name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  RESOURCE_GROUP: MCS09
  CONTAINER_APP_NAME: mcs09-backend
  CONTAINER_APP_ENV: mcs09-backend-env
  ACR_NAME: MCS09registry
  LOCATION: westus2
  SUBSCRIPTION_ID: "4e50719f-b88a-461c-82a2-c522104e3cc9"
  TENANT_ID: "ef7a487a-77ca-410a-803d-e426b62a587f"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure login with OIDC
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ env.TENANT_ID }}
        subscription-id: ${{ env.SUBSCRIPTION_ID }}

    - name: ACR Login
      run: |
        az acr login --name ${{ env.ACR_NAME }}

    - name: Build and Push to ACR
      run: |
        az acr build \
          --registry ${{ env.ACR_NAME }} \
          --image ${{ env.CONTAINER_APP_NAME }}:${{ github.sha }} \
          --file Dockerfile \
          .

    - name: Deploy to Azure Container Apps
      uses: Azure/container-apps-deploy-action@v2
      with:
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        containerAppEnvironment: ${{ env.CONTAINER_APP_ENV }}
        location: ${{ env.LOCATION }}
        targetPort: 80
        ingress: external
        image: ${{ env.ACR_NAME }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}

    - name: Get Container App URL
      run: |
        DOMAIN=$(az containerapp show \
          --name ${{ env.CONTAINER_APP_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --query properties.configuration.ingress.fqdn \
          --output tsv)
        echo "Application is available at: https://$DOMAIN"
