name: Build and Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Enables manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Azure CLI Login
      run: |
        az login --use-device-code
      
    - name: Set Azure Subscription
      run: |
        az account set --subscription "4e50719f-b88a-461c-82a2-c522104e3cc9"

    - name: Build and deploy Container App
      uses: Azure/container-apps-deploy-action@v2
      with:
        acrName: MCS09registry
        containerAppName: mcs09-backend
        resourceGroup: MCS09
        appSourcePath: ${{ github.workspace }}
